# Generated by Django 2.2.4 on 2019-08-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clustermap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
    ]
